on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go run ./internal/ci/bump/main.go
      - run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "GitHub Action"
            git config user.email "action@github.com"

            git checkout -B ci/bump
            git add ./packages

            git commit -m "packages: Update packages to latest versions"
            git push origin ci/bump --force

            if ! gh pr view ci/bump &> /dev/null; then
              gh pr create --base main --head ci/bump --title 'ci: Update packages to latest versions' --body ''
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
